spring.application.name=student

spring.datasource.url=jdbc:mysql://localhost:3306/studentsdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=20261026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085